---
# Replace hosts
- name: System | Configure /etc/hosts
  template: src=../files/hosts dest=/etc/hosts mode=0600

# Update Apt Repository

- name: System | Update Repository
  apt: update_cache=yes

- name: System | Install Various Packages
  apt: pkg={{ item }} state=installed
  with_items:
    - unzip

# Python Requirements

- name: System | Install python-software-properties
  apt: pkg=python-software-properties state=installed

- name: System | Install Build-Essentials
  apt: pkg=build-essential state=installed

# ACL - for easy access control management

- name: System | Install ACL
  apt: pkg=acl state=installed

# cURL

- name: System | Install cURL
  apt: pkg=curl state=installed

# Git

- name: System | Install Git
  apt: pkg=git-core state=installed

# Host Configuration

- name: System | Set hostname
  hostname: name={{ hostname }}
